apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probebbox
  name: probebbox
spec:
 containers:
 - image: busybox
   args:
   - sleep
   - "3600"
   name: probebbox
   resources: {}
   livenessProbe:
     initialDelaySeconds: 5
     periodSeconds: 1
     exec:
       command: 
       - cat 
       - /etc/hosts
