apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probe_bbox
  name: probe_bbox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: probe_bbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
