apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbox
  name: bbox
spec:
  serviceAccountName: mynewsa
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: bbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
