apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: secret
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: pod
    resources:
      requests:
        memory: "64M"
      limits:
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure 
status: {}
