apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-07-31T15:34:03Z"
  generation: 3
  labels:
    app: mapnginx
  name: mapnginx
  namespace: default
  resourceVersion: "163835"
  uid: c7b3ea9e-e2ef-4822-81cf-295aea3d5878
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mapnginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mapnginx
    spec:
      containers:
      - env:
        - name: MYPASS
          valueFrom:
            secretKeyRef:
              key: MYPASSWORD
              name: my-secret
        image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: indexmap
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-31T15:34:05Z"
    lastUpdateTime: "2024-07-31T15:34:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-31T15:34:03Z"
    lastUpdateTime: "2024-07-31T15:49:06Z"
    message: ReplicaSet "mapnginx-765d6958b6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
