apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lab5
  labels:
    role: myrole
spec:
  containers:
    - name: nginx-prod
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
