apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: labnginx
    type: proxy
  name: labnginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: labnginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: labnginx
    spec:
      containers:
      - image: nginx:1.9
        name: nginx
        resources: {}
status: {}
